#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: 1234
#    dbname: test
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl